day3/Models/ApplicatoinDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;


namespace VidlysProject.Models
{
    public class ApplicatoinDbContext : DbContext
    {
         public DbSet<Customer> Customers { get; set; }
    }
}

day3/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VidlysProject.Models
{
    public class Customer
    {
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        public bool IsSuscribedToNewsletter { get; set; }
        public MembershipType MembershipType { get; set; }
        public byte MembershipTypeId  { get; set; }
    }
}

day3/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VidlysProject.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

day3/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidlysProject.Models;
using System.Data.Entity;

namespace VidlysProject.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicatoinDbContext _context;

        public CustomerController()
        {
            _context = new ApplicatoinDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ActionResult Index()
        {
            var customer = _context.Customers.Include(c=>c.MembershipType).ToList();

            return View(customer);
        }
        public ActionResult Details(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return HttpNotFound();

            return View(customer);
        }
        
    }
}

day3/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using VidlysProject.Models;
using VidlysProject.ViewModels;

namespace VidlysProject.Controllers
{
    public class MovieController : Controller
    {

   
        public ActionResult Index()
        {

            Movie movie = new Movie() { Name = "WorldWar-Z" };

           

            var viewmodel = new RamdomMovieViewModel
            {

                Movie = movie,
               
            };
            return View(viewmodel);



            // return Content("Hello World");
            //return HttpNotFound();
            //  return new EmptyResult();


            // return RedirectToAction("Index","Home",new {page=1,sortby="name"});


        }

        public ActionResult CustomerName()
        {
            var customer = new List<Customer> {

                new Customer{ Name="Jeet Kini"},
                new Customer{ Name="Adnan khan"}
            };
            var viewmodel = new RamdomMovieViewModel
            {


                Customers = customer
            };
            return View(viewmodel);
        }
        public ActionResult Movies()
        {
            ViewBag.Name = "WorldWar-Z";
            return View();
        }
        public ActionResult Details()
        {
            ViewBag.Name = "Jeet Kini";



            return View();

        }
        public ActionResult Edit(int id)
        {

            return Content("id :" + id);
        }
        public ActionResult Index1(int? pageIndex, string sortBy)
        {
            if (pageIndex != 0)
            {
                pageIndex = 1;
            }
            if (String.IsNullOrEmpty(sortBy))
            {
                sortBy = "name";
            }
            return Content(String.Format("pageIndex :{0} sortBy :{1}", pageIndex, sortBy));

        }
    }
}

day3/Views/Customer/Details.cshtml
@model VidlysProject.Models.Customer
@{
    ViewBag.Title = "Details";
}


﻿
<h2>@Model.Name</h2>



day3/Views/Customer/Index.cshtml
@model IEnumerable<VidlysProject.Models.Customer>
@{
    ViewBag.Title = "Index";
}
<h1>
    CUSTOMERS
</h1>
@if (!Model.Any())
{
    <p>We Dont have any customer yet.</p>
}
else
{
    <table class="table table-bordered table-hover"  >
        <thead>

            <tr>
                <th>Customer</th>
                @*<th>Discount Rate</th>*@
                <th>Membership Type</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
<tr>
    <td>
        @Html.ActionLink(customer.Name, "Details", "Customer", new { id = customer.Id }, null)
    </td>
    @*<td>@customer.MembershipType.DiscountRate% </td>*@
    <td>@customer.MembershipType.DurationInMonths</td>
</tr>
        }
            </tbody>
        </table>


    }





day3/Views/Movie/Details.cshtml

@{
    ViewBag.Title = "Details";
}

<h2>@ViewBag.Name</h2>



day3/Views/Movie/Index.cshtml
@model VidlysProject.ViewModels.RamdomMovieViewModel
@{
    ViewBag.Title = "Index";
}

<h2>@Model.Movie.Name</h2>
@if (Model.Customers.Count == 0)
{
    <text>NO one has rented this Movie Before</text>
}
else
{
    <ul>
        @foreach (var item in Model.Customers)
        {
            <li>@item.Name</li>
        }
    </ul>
}


day3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("VIDLYS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Customer", "Index","Customer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Movies", "Movies","Movie", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li>aaaaaaaaaa</li>

                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit" style="hight:2px">Search</button>
                    </form>
                    <li>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</li>
                    
                    
                    <li>@Html.ActionLink("Register", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Login", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>

            </div>
            
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VIDLYS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>